final List<String> personality = [
  "Active/lively",
  "Cheerful",
  "Generous",
  "Modest",
  "Shy",
  "Self-confident",
  "Ambitious",
  "Calm",
  "Fun",
  "Cultivated",
  "Imaginative",
  "Moody",
  "Reliable",
  "Independent",
  "Open-minded",
  "Spiritual",
  "Sociable",
  "Sensitive",
  "chatty",
  "Mature",
  "Sophisticatedy",
  "Outgoing/ Talkative",
  "Honest/ Frank",
  "Relaxed/ Casual",
];

final List<String> sport = [
  "Aerobics",
  "Biliards/ Pool",
  "Golf",
  "Bowling",
  "Football",
  "Hockey",
  "Baseball",
  "Basketball",
  "Cycling",
  "Independent",
  "Watersports",
  "Swimming",
  "Volleyball",
  "Rugby",
  "Inline/ Ice skating",
  "Skiing/ Snowboarding",
  "Walking/ Hiking",
  "Horseback riding",
  "Running/ Cardio",
  "Tennis/ Racquet Sports",
  "Auto racing/ Motorcross"
];

final List<String> hobbies = [
  "Art & Craft",
  "Cooking/ Baking",
  "Hiking",
  "Video game",
  "Working out",
  "Fishing/ Hunting",
  "Pets/ Animals",
  "Gardning",
  "Networking/ Socialising",
  "Playing cards/ Board gems",
  "Museums/ Galleries",
  "Shopping/ Antiques",
  "Religion/ Spirituality",
  "Wine or Food Tasting",
  "Watching Sports",
  "Book or Discussion clubs",
  "Night clubs/ Dancing",
  "Music/ Concerts",
  "Coffee/ Conversation",
  "Performing arts/ Theatre",
  "Traveling/ Sightseeing",
  "Charities/ Organisation",
];

final List<String> looking = [
  "Platonic",
  "Short-Term",
  "Friendship",
  "Long- Term",
  "Soulmate",
  "Loving",
  "Romantic",
  "Playful",
  "Chatting",
  "Complicity",
  "Passionate",
  "Swinning",
  "Learning/ Exchanging",
  "Companionship",
  "Discretion/ Secrecy",
  "Just a fling",
  "No perticular expectation",
  "One-night-stand",
  "Purely sexual",
  "Experience sharing",
  "No strings attached",
  "Something serious",
  "Homosexual/ Bisexual",
  "Taking things slow",
];

final List<String> relationship = [
  "Anything exciting",
  "Long term",
  "Open to anything",
  "Short term",
  "Undecided",
  "Virtual",
];

final List<String> sexualpractises = [
  "Anything goes",
  "Conventional sex only",
  "Reading erotic literature",
  "Threesome (or more)",
  "Being dominated",
  "Dominating",
  "Romantic sex",
  "Watching erotic movies",
  "Being blind folded",
  "Costumes",
  "Role playing",
  "Using sex toy",
  "Being watched",
  "I’d rather not say. That’s private",
  "Sex in unusual places"
];

final List<String> games = [
  "Personality",
  "Sport activity",
  "Hobbies",
  "Politics",
  "Film industry",
  "Tech",
];
